Automatically Install & Activate the Import Users from CSV plugin
strangerstudios/pmpro-import-users-from-csv pull request #33
Opened 2021-11-03 12:08 UTC by JarrydLong

2022-02-24 05:32 UTC, sc0ttkclark commented on pmpro-import-users-from-csv.php
> +        <p><?php printf( __( 'In order for <strong>Paid Memberships Pro - Import Users from CSV</strong> to function correctly, you must also install the <a href="%s">Import Users from CSV</a> plugin
We could bypass the need for a hidden page for installing and just use a link like this:

```php
$url = wp_nonce_url(
	add_query_arg(
		[
			'action' => 'install-plugin',
			'plugin' => 'import-users-from-csv',
			'from'   => 'import',
		],
		admin_url( 'update.php' )
	),
	'install-plugin_import-users-from-csv'
);
```

and then pass that into line 71 for the link.

2022-02-24 05:33 UTC, sc0ttkclark commented on pmpro-import-users-from-csv.php
> +
Let's go the simpler route and use the built-in plugin installation page

2022-02-24 05:37 UTC, sc0ttkclark commented on pmpro-import-users-from-csv.php
> +        <p><?php printf( __( 'In order for <strong>Paid Memberships Pro - Import Users from CSV</strong> to function correctly, you must also install the <a href="%s">Import Users from CSV</a> plugin
Before showing the link, we also need to check if they have the correct capability to install plugins.

`current_user_can( 'install_plugins' )`

If the plugin is already installed but needs to be activated, we can use this link:

```php
$url = wp_nonce_url(
	add_query_arg(
		[
			'action' => 'activate',
			'plugin' => 'import-users-from-csv',
		],
		admin_url( 'plugins.php' )
	),
	'activate-plugin_import-users-from-csv'
);
```

Before showing the activate link itself, we should also check for access rights by checking `current_user_can( 'activate_plugin', 'import-users-from-csv' )`

2022-02-24 05:37 UTC, sc0ttkclark requested changes
Needs a new approach

2022-02-24 05:42 UTC, JarrydLong commented on pmpro-import-users-from-csv.php
> +
I'm not sure I understand, which plugin installation page?

2022-03-05 02:31 UTC, sc0ttkclark approved these changes

2022-03-10 15:41 UTC, sc0ttkclark commented on pmpro-import-users-from-csv.php
> +			'activate-plugin_import-users-from-csv'
```suggestion
					'plugin' => 'import-users-from-csv/import-users-from-csv.php',
				],
				admin_url( 'plugins.php' )
			),
			'activate-plugin_import-users-from-csv/import-users-from-csv.php'

```

2022-03-10 15:49 UTC, merged