Supress change membership level option added
strangerstudios/pmpro-import-users-from-csv pull request #36
Opened 2021-11-11 06:38 UTC by JarrydLong

Needs some discussion though. Could also do this (might be better) but we don't hook much into the before and after actions in the core plugin

```
if( !empty( $_REQUEST['supress_change'] ) && $_REQUEST['supress_change'] == '1' ){
			remove_action("pmpro_after_change_membership_level", "pmpro_report_memberships_delete_transients");
		}
```

2022-02-09 09:42 UTC, andrewlimaza commented
I think it's good to include this not to waste resources on imports. I imagine 1000 user records being imported and then it deletes the transients 1000 times.

2022-02-24 05:41 UTC, sc0ttkclark commented on pmpro-import-users-from-csv.php
> +		$membership_code_id = $wpdb->get_var("SELECT id FROM $wpdb->pmpro_discount_codes WHERE `code` = '" . esc_sql($membership_discount_code) . "' LIMIT 1");
Let's use `$wpdb->prepare()` for any new queries we create, it ensures we follow coding best-practices for queries with WP and also helps avoid where WP dev docs says to avoid using `esc_sql()` in this way.

```suggestion
		$membership_code_id = $wpdb->get_var(
			$wpdb->prepare( "
				SELECT id
				FROM $wpdb->pmpro_discount_codes
				WHERE `code` = %s
				LIMIT 1
			", $membership_discount_code );
```

2022-02-24 05:42 UTC, sc0ttkclark commented on pmpro-import-users-from-csv.php
> +	if( pmpro_hasMembershipLevel( $membership_id, $user_id ) && ( !empty( $_REQUEST['supress_change_membership_hooks'] ) && $_REQUEST['supress_change_membership_hooks'] == '1' ) ){
We can simplify the logic here since it will either be set as 1 or not set/empty.

```suggestion
	if( pmpro_hasMembershipLevel( $membership_id, $user_id ) && ! empty( $_REQUEST['supress_change_membership_hooks'] ) ){
```

2022-02-24 05:42 UTC, sc0ttkclark commented on pmpro-import-users-from-csv.php
> +					<?php _e( 'Supress change membership level hooks during import?', 'pmpro-import-users-from-csv' ) ;?>
```suggestion
					<?php esc_html_e( 'Supress change membership level hooks during import?', 'pmpro-import-users-from-csv' ) ;?>

```

2022-02-24 05:42 UTC, sc0ttkclark commented on pmpro-import-users-from-csv.php
> +		<td scope="row"><strong><?php _e( 'Supress Change Membership Level Hooks' , 'pmpro-import-users-from-csv'); ?></strong></td>
```suggestion
		<td scope="row"><strong><?php esc_html_e( 'Supress Change Membership Level Hooks' , 'pmpro-import-users-from-csv'); ?></strong></td>

```

2022-02-24 05:42 UTC, sc0ttkclark commented on pmpro-import-users-from-csv.php
> +				<legend class="screen-reader-text"><span><?php _e( 'Supress Change Membership Level Hooks' , 'pmpro-import-users-from-csv' ); ?></span></legend>
```suggestion
				<legend class="screen-reader-text"><span><?php esc_html_e( 'Supress Change Membership Level Hooks' , 'pmpro-import-users-from-csv' ); ?></span></legend>

```

2022-02-24 05:43 UTC, sc0ttkclark requested changes
Be sure to escape translated text with esc_html_e() instead of _e() where HTML is not expected. Additional tweaks recommended too.

2022-03-05 03:21 UTC, sc0ttkclark approved these changes

2022-03-10 15:29 UTC, sc0ttkclark commented
Intention for this PR as discussed with Andrew:

Check the box and stop cancelling of subscriptions

2022-03-10 15:39 UTC, sc0ttkclark commented
Andrew's other PR #37 replaces the need for what this PR is doing right now -- however it makes sense to have a checkbox that notes the intention "Skip if they already have the same membership level" or similar.

2022-03-10 16:17 UTC, merged